# Setup Docker on Raspberri Ubuntu
---
# Playbook for the worker nodes
- hosts: all
  become: true

  tasks:
    - name: Get architecture
      shell: dpkg --print-architecture
      register: architecture_output

    - name: Get release
      shell: lsb_release -cs
      register: release_output

    - set_fact:
        architecture: "{{ architecture_output.stdout }}"
        release: "{{ release_output.stdout }}"

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch={{ architecture }}] https://download.docker.com/linux/ubuntu {{ release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

- hosts: control
  become: true
  tasks:
    - name: Run Portainer Docker container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        ports:
          - "8000:8000"
          - "9443:9443"
        restart_policy: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"

- hosts: workers
  become: true
  tasks:
    - name: Run Portainer Agent Docker container
      docker_container:
        name: portainer_agent
        image: portainer/agent:2.19.5
        ports:
          - "9001:9001"
        restart_policy: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"
